### ISSUE TITLE
Posting a unicode post(data=someutf8) gives UnicodeEncodeError

### ISSUE THREAD

**Issue by illume** [paivett/requests-curl#3]
requests seems to allow this, but requests_curl requires a bytes object, otherwise it tries to encode the data with `ascii`. If the unicode contains ü (metal dots) then encoding to ascii fails.

pycurl docs: http://pycurl.io/docs/latest/unicode.html#setting-options-python-3-x

The work around is to pass data as a bytes object.
```
someutf8= 'ü'
requests.post(url, data=bytes(someutf8, 'utf-8')) 
```

I'm not sure of the correct fix... needs some thought.

**Comment by paivett** [comment]
Quite late, sorry, but I pushed a fix. Now every request ensures that the body is encoded using six.ensure_binary. By default it uses utf-8. Maybe later I could add support for other encodings.

**Comment by illume** [comment]
Nice one :)

**Comment by paivett** [comment]
I had to apply some changes in how the body options are built for your example to work as requests works, otherwise my implementation was always sending a url-encoded form.
Now it seems to be more aligned to how requests works, although there are still some corner cases, but for now it seems good enough.
